# Generated by Django 4.1.5 on 2023-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
