# Generated by Django 4.1.5 on 2023-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
