# Generated by Django 4.1.5 on 2023-01-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0004_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to=""
            ),
        ),
    ]
